version: 2.1

jobs:
 build:
   machine: true
   steps:
     #- checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login --username $DOCKER_USER --password-stdin
         docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
 deploy:
   executor: heroku/default
   steps:
     - checkout
     - heroku/install
     - heroku/check-authentication
     - run:
         command: >
           echo "The command above installs Heroku, the command below deploys.
           What you do inbetween is up to you!"
     - heroku/deploy-via-git         

orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.4

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  heroku_deploy:
    jobs:
      - build
      - deploy
      #- heroku/deploy-via-git
      #- heroku/push-docker-image
