orbs:
  heroku: circleci/heroku@1.2.4
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: echo "your-database-migration-command"
          pre-steps:
            - run: echo "command-that-run-before-deploying"
            - run: heroku login
