machine:
  services:
    - docker

deployment:
  production:
    branch: main
    commands:
      - docker build -t app-deploy-to-heroku .
      #- docker login --email=_ --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      #- docker tag  app-deploy-to-heroku:latest registry.heroku.com/app-deploy-to-heroku/web
      #- docker push registry.heroku.com/app-deploy-to-heroku/web
