version: 2.1

jobs:
 login:
   machine: true
   steps:
     - run:
         echo "test"
 build:
   machine: true
   steps:
     #- checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     #docker login --username $DOCKER_USER --password-stdin
     #docker login --username=$HEROKU_LOGIN --password-stdin=$HEROKU_API_KEY registry.heroku.com           
     - run:       
         echo "$DOCKER_PASSWORD"  | docker login --username $DOCKER_LOGIN --password-stdin         
         
 deploy:
   executor: heroku/default
   steps:
     - checkout
     - heroku/install
     - heroku/check-authentication     
     #- run:
         #heroku auth:token    
     #- heroku/deploy-via-git  
     - run:
        systemctl start docker
     - heroku/push-docker-image

orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.4

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  heroku_deploy:
    jobs:
      - login
      - build
      - deploy
      #- heroku/deploy-via-git
      #- heroku/push-docker-image
