version: 2.1

orbs:
    heroku: circleci/heroku@1.2.2

jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01
        
    steps:
      - setup_remote_docker
      
workflows:
  heroku_deploy:
    jobs:
      - heroku/push-docker-image
