jobs:
  init:
    executor: heroku/default
    steps:        
     - setup_remote_docker:
         version: 19.03.13 
         
version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.4

workflows:
  deploy:    
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  heroku_deploy:
    jobs:
      - init
      - heroku/push-docker-image
