version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01
    
    working_directory: ~/app-to-deploy-to-heroku
    
    steps:
      - checkout
      
orbs:
    heroku: circleci/heroku@1.2.2

workflows:
  heroku_deploy:
    jobs:
      - heroku/push-docker-image
